Digic 6 support, 750D, 200D and R into LV, scripts and fixes
reticulatedpines/magiclantern_simplified pull request #25
Opened 2021-10-16 17:18 UTC by kitor

* Added support for full build of DIGIC6 cameras
* Dialog structs for D6, D7 and EOSR (not "D8" yet as M/RP not tested, RP is known to differ in size)
* New cam supported: 750D - features on par with 200D,R
* 750D, 200D and R have working Global draw in LV + overlays feature
* R: Experimental support for CONFIG_RESTORE_AFTER_FORMAT
* Fixes in rbf_font, propvalues
* Scripts for decoding D8 palette resources and D7/D8 EDMAC Config

2021-10-21 22:26 UTC, reticulatedpines commented
Taken with tweaks into d6_plus_d678_lv

2021-10-22 14:10 UTC, reticulatedpines requested changes
A test comment for "finish your review" part of the process

2021-10-22 14:10 UTC, reticulatedpines commented on src/lvinfo.c
> +            if (i < count) prev_right = items[i]->x + items[i]->width/2;
Let's split this into a two-line indented if, to test this workflow

2021-10-22 14:20 UTC, kitor commented on src/lvinfo.c
> +            if (i < count) prev_right = items[i]->x + items[i]->width/2;
Updated in 242ce8130

2021-10-22 14:24 UTC, merged